// attribute.go.

////////////////////////////////////////////////////////////////////////////////
//
// Copyright © 2019..2020 by Vault Thirteen.
//
// All rights reserved. No part of this publication may be reproduced,
// distributed, or transmitted in any form or by any means, including
// photocopying, recording, or other electronic or mechanical methods,
// without the prior written permission of the publisher, except in the case
// of brief quotations embodied in critical reviews and certain other
// noncommercial uses permitted by copyright law. For permission requests,
// write to the publisher, addressed “Copyright Protected Material” at the
// address below.
//
////////////////////////////////////////////////////////////////////////////////
//
// Web Site Address:	https://github.com/vault-thirteen.
//
////////////////////////////////////////////////////////////////////////////////

package main

// HTML Attributes.
const (
	AttributeAccept          = "accept"
	AttributeAcceptCharset   = "accept-charset"
	AttributeAccesskey       = "accesskey"
	AttributeAction          = "action"
	AttributeAlign           = "align"
	AttributeAllow           = "allow"
	AttributeAlt             = "alt"
	AttributeAsync           = "async"
	AttributeAutocapitalize  = "autocapitalize"
	AttributeAutocomplete    = "autocomplete"
	AttributeAutofocus       = "autofocus"
	AttributeAutoplay        = "autoplay"
	AttributeBackground      = "background"
	AttributeBgcolor         = "bgcolor"
	AttributeBorder          = "border"
	AttributeBuffered        = "buffered"
	AttributeCapture         = "capture"
	AttributeChallenge       = "challenge"
	AttributeCharset         = "charset"
	AttributeChecked         = "checked"
	AttributeCite            = "cite"
	AttributeClass           = "class"
	AttributeCode            = "code"
	AttributeCodebase        = "codebase"
	AttributeColor           = "color"
	AttributeCols            = "cols"
	AttributeColspan         = "colspan"
	AttributeContent         = "content"
	AttributeContenteditable = "contenteditable"
	AttributeContextmenu     = "contextmenu"
	AttributeControls        = "controls"
	AttributeCoords          = "coords"
	AttributeCrossorigin     = "crossorigin"
	AttributeCsp             = "csp "
	AttributeData            = "data"
	AttributeDatetime        = "datetime"
	AttributeDecoding        = "decoding"
	AttributeDefault         = "default"
	AttributeDefer           = "defer"
	AttributeDir             = "dir"
	AttributeDirname         = "dirname"
	AttributeDisabled        = "disabled"
	AttributeDownload        = "download"
	AttributeDraggable       = "draggable"
	AttributeDropzone        = "dropzone"
	AttributeEnctype         = "enctype"
	AttributeEnterkeyhint    = "enterkeyhint "
	AttributeFor             = "for"
	AttributeForm            = "form"
	AttributeFormaction      = "formaction"
	AttributeFormenctype     = "formenctype"
	AttributeFormmethod      = "formmethod"
	AttributeFormnovalidate  = "formnovalidate"
	AttributeFormtarget      = "formtarget"
	AttributeHeaders         = "headers"
	AttributeHeight          = "height"
	AttributeHidden          = "hidden"
	AttributeHigh            = "high"
	AttributeHref            = "href"
	AttributeHreflang        = "hreflang"
	AttributeHttpEquiv       = "http-equiv"
	AttributeIcon            = "icon"
	AttributeId              = "id"
	AttributeImportance      = "importance "
	AttributeIntegrity       = "integrity"
	AttributeIntrinsicsize   = "intrinsicsize "
	AttributeInputmode       = "inputmode"
	AttributeIsmap           = "ismap"
	AttributeItemprop        = "itemprop"
	AttributeKeytype         = "keytype"
	AttributeKind            = "kind"
	AttributeLabel           = "label"
	AttributeLang            = "lang"
	AttributeLanguage        = "language"
	AttributeLoading         = "loading "
	AttributeList            = "list"
	AttributeLoop            = "loop"
	AttributeLow             = "low"
	AttributeManifest        = "manifest"
	AttributeMax             = "max"
	AttributeMaxlength       = "maxlength"
	AttributeMinlength       = "minlength"
	AttributeMedia           = "media"
	AttributeMethod          = "method"
	AttributeMin             = "min"
	AttributeMultiple        = "multiple"
	AttributeMuted           = "muted"
	AttributeName            = "name"
	AttributeNovalidate      = "novalidate"
	AttributeOpen            = "open"
	AttributeOptimum         = "optimum"
	AttributePattern         = "pattern"
	AttributePing            = "ping"
	AttributePlaceholder     = "placeholder"
	AttributePoster          = "poster"
	AttributePreload         = "preload"
	AttributeRadiogroup      = "radiogroup"
	AttributeReadonly        = "readonly"
	AttributeReferrerpolicy  = "referrerpolicy"
	AttributeRel             = "rel"
	AttributeRequired        = "required"
	AttributeReversed        = "reversed"
	AttributeRows            = "rows"
	AttributeRowspan         = "rowspan"
	AttributeSandbox         = "sandbox"
	AttributeScope           = "scope"
	AttributeScoped          = "scoped"
	AttributeSelected        = "selected"
	AttributeShape           = "shape"
	AttributeSize            = "size"
	AttributeSizes           = "sizes"
	AttributeSlot            = "slot"
	AttributeSpan            = "span"
	AttributeSpellcheck      = "spellcheck"
	AttributeSrc             = "src"
	AttributeSrcdoc          = "srcdoc"
	AttributeSrclang         = "srclang"
	AttributeSrcset          = "srcset"
	AttributeStart           = "start"
	AttributeStep            = "step"
	AttributeStyle           = "style"
	AttributeSummary         = "summary"
	AttributeTabindex        = "tabindex"
	AttributeTarget          = "target"
	AttributeTitle           = "title"
	AttributeTranslate       = "translate"
	AttributeType            = "type"
	AttributeUsemap          = "usemap"
	AttributeValue           = "value"
	AttributeWidth           = "width"
	AttributeWrap            = "wrap"
)

// Source:
// https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes
